class_name SpeciesLibrary
extends RefCounted
## The bestiary. Raw tables here, [Species] objects built on demand.

## Voice parameters handed to [Synth.animal_call]. Kept as a plain const so the
## audio thread can read it without touching anything else.
const CALL_PARAMS := {
	"whitetail_deer": {"base": 300.0, "end": 210.0, "dur": 0.45, "rough": 0.25,
		"rough_hz": 34.0, "breath": 0.18, "harmonics": 6, "tone": 3200.0, "space": 0.3},
	"red_stag": {"base": 180.0, "end": 620.0, "dur": 2.1, "rough": 0.12, "rough_hz": 9.0,
		"breath": 0.14, "harmonics": 9, "wobble": 12.0, "wobble_hz": 4.5, "curve": 0.6,
		"tone": 4200.0, "space": 0.5, "release": 0.45},
	"moose": {"base": 130.0, "end": 96.0, "dur": 1.6, "rough": 0.3, "rough_hz": 16.0,
		"breath": 0.22, "harmonics": 8, "tilt": 1.0, "tone": 1800.0, "space": 0.42},
	"grey_wolf": {"base": 340.0, "end": 300.0, "dur": 2.6, "rough": 0.05, "rough_hz": 5.0,
		"breath": 0.06, "harmonics": 7, "wobble": 9.0, "wobble_hz": 1.6, "curve": 0.4,
		"tone": 3600.0, "space": 0.62, "attack": 0.22, "release": 0.4},
	"red_fox": {"base": 780.0, "end": 540.0, "dur": 0.32, "rough": 0.4, "rough_hz": 55.0,
		"breath": 0.2, "harmonics": 5, "tone": 5200.0, "space": 0.34},
	"brown_bear": {"base": 92.0, "end": 68.0, "dur": 1.5, "rough": 0.55, "rough_hz": 22.0,
		"breath": 0.3, "harmonics": 9, "tilt": 0.9, "tone": 1400.0, "space": 0.3},
	"wild_boar": {"base": 220.0, "end": 150.0, "dur": 0.5, "rough": 0.6, "rough_hz": 44.0,
		"breath": 0.35, "harmonics": 6, "tone": 2600.0, "space": 0.22},
	"snowshoe_hare": {"base": 620.0, "end": 900.0, "dur": 0.22, "rough": 0.2,
		"rough_hz": 60.0, "breath": 0.24, "harmonics": 4, "tone": 6000.0, "space": 0.2},
	"horned_owl": {"base": 260.0, "end": 240.0, "dur": 1.3, "rough": 0.08, "rough_hz": 3.0,
		"breath": 0.04, "harmonics": 3, "tilt": 2.2, "tone": 1200.0, "space": 0.55},
	"raven": {"base": 430.0, "end": 300.0, "dur": 0.42, "rough": 0.7, "rough_hz": 70.0,
		"breath": 0.3, "harmonics": 7, "tone": 4400.0, "space": 0.45},
	"mallard": {"base": 520.0, "end": 380.0, "dur": 0.3, "rough": 0.75, "rough_hz": 90.0,
		"breath": 0.26, "harmonics": 6, "tone": 4800.0, "space": 0.25},
	"bighorn_ram": {"base": 210.0, "end": 170.0, "dur": 0.7, "rough": 0.45, "rough_hz": 30.0,
		"breath": 0.2, "harmonics": 7, "tone": 3000.0, "space": 0.6},
	"pronghorn": {"base": 480.0, "end": 360.0, "dur": 0.28, "rough": 0.35, "rough_hz": 50.0,
		"breath": 0.28, "harmonics": 5, "tone": 5000.0, "space": 0.3},
	"bobcat": {"base": 560.0, "end": 380.0, "dur": 0.85, "rough": 0.5, "rough_hz": 26.0,
		"breath": 0.16, "harmonics": 6, "wobble": 20.0, "wobble_hz": 5.0, "tone": 4600.0,
		"space": 0.35},
	"river_otter": {"base": 900.0, "end": 1250.0, "dur": 0.2, "rough": 0.3, "rough_hz": 70.0,
		"breath": 0.18, "harmonics": 4, "tone": 6400.0, "space": 0.28},
	# The legendaries get voices you can pick out of a forest, because hearing
	# one is usually how you learn it is there at all.
	"albino_deer": {"base": 280.0, "end": 190.0, "dur": 0.6, "rough": 0.18,
		"rough_hz": 26.0, "breath": 0.22, "harmonics": 7, "tone": 3000.0, "space": 0.72,
		"release": 0.5},
	"black_wolf": {"base": 240.0, "end": 205.0, "dur": 3.4, "rough": 0.04, "rough_hz": 4.0,
		"breath": 0.05, "harmonics": 9, "wobble": 7.0, "wobble_hz": 1.1, "curve": 0.35,
		"tone": 2800.0, "space": 0.85, "attack": 0.3, "release": 0.7},
	"golden_eagle": {"base": 1450.0, "end": 980.0, "dur": 0.55, "rough": 0.55,
		"rough_hz": 46.0, "breath": 0.16, "harmonics": 5, "wobble": 26.0, "wobble_hz": 9.0,
		"tone": 7200.0, "space": 0.7},
}

const DATA := [
	{
		"id": "whitetail_deer", "name": "Whitetail Deer", "latin": "Odocoileus virginianus",
		"family": "Cervidae", "size_class": "medium", "rarity": 0.10, "shape": "deer",
		"palette": {"primary": Color(0.55, 0.38, 0.24), "secondary": Color(0.72, 0.58, 0.42),
			"accent": Color(0.94, 0.92, 0.87), "dark": Color(0.22, 0.16, 0.11)},
		"shoulder_height": 1.05, "body_length": 1.8, "body_scale": 1.0,
		"speed_walk": 1.5, "speed_run": 12.0, "turn_rate": 3.4,
		"vision_range": 60.0, "vision_angle": 260.0, "hearing_range": 45.0,
		"scent_range": 80.0, "wariness": 0.62, "flee_distance": 26.0, "curiosity": 0.25,
		"biomes": {"emerald_vale": 1.0, "amber_woods": 1.0, "golden_steppe": 0.4,
			"mistwood_marsh": 0.35},
		"active_hours": [[4.5, 9.0], [16.5, 21.0]],
		"herd_min": 1, "herd_max": 4, "near_water": 0.3,
		"diet": "Browses on shoots, acorns and fallen fruit; drawn to forest edges at first light.",
		"habitat_note": "Mixed woodland with open clearings. Beds down in thickets through the middle of the day.",
		"behaviour_note": "Flags its white tail when alarmed and bounds away in a curving line. Freezes before it runs - that pause is your shot.",
		"features_note": "Bucks carry forward-curving antlers that drop in late winter. Reddish in summer, grey-brown by the rut.",
		"track_note": "Two teardrop halves, points forward, about 7 cm long. Dew claws show in soft ground.",
		"track_shape": "cloven", "track_size": 0.30,
		"has_antlers": true, "antler_points": Vector2i(4, 10),
		"weight_range": Vector2(52.0, 130.0), "photo_value": 40,
		"behaviours": ["grazing", "browsing", "alert", "walking", "resting", "fleeing", "scraping"],
	},
	{
		"id": "red_stag", "name": "Red Stag", "latin": "Cervus elaphus",
		"family": "Cervidae", "size_class": "large", "rarity": 0.45, "shape": "elk",
		"palette": {"primary": Color(0.46, 0.29, 0.17), "secondary": Color(0.62, 0.44, 0.27),
			"accent": Color(0.85, 0.78, 0.62), "dark": Color(0.17, 0.12, 0.08)},
		"shoulder_height": 1.35, "body_length": 2.3, "body_scale": 1.25,
		"speed_walk": 1.7, "speed_run": 11.0, "turn_rate": 2.6,
		"vision_range": 70.0, "vision_angle": 250.0, "hearing_range": 55.0,
		"scent_range": 95.0, "wariness": 0.72, "flee_distance": 36.0, "curiosity": 0.15,
		"biomes": {"amber_woods": 1.0, "alpine_ridge": 0.6, "emerald_vale": 0.5,
			"boreal_taiga": 0.4},
		"active_hours": [[5.0, 9.5], [17.0, 22.0]],
		"herd_min": 2, "herd_max": 7, "near_water": 0.25,
		"altitude_pref": Vector2(26.0, 70.0),
		"diet": "Grasses, heather and bark stripped from young trees in hard weather.",
		"habitat_note": "Open hillsides above the treeline in summer, dropping into sheltered woods when the wind turns.",
		"behaviour_note": "Bugles at dawn through the autumn rut. Herds post a sentinel that lifts its head every few seconds.",
		"features_note": "Heavy branched antlers with brow, bez and trey tines. A mature stag carries a shaggy neck mane.",
		"track_note": "Large cloven print, blunt at the tip, 9 cm and deep-set from the weight.",
		"track_shape": "cloven", "track_size": 0.40,
		"has_antlers": true, "antler_points": Vector2i(8, 16),
		"weight_range": Vector2(120.0, 240.0), "photo_value": 85,
		"call_chance": 0.75,
		"behaviours": ["grazing", "bugling", "alert", "walking", "resting", "fleeing", "sparring"],
	},
	{
		"id": "moose", "name": "Moose", "latin": "Alces alces",
		"family": "Cervidae", "size_class": "large", "rarity": 0.62, "shape": "moose",
		"palette": {"primary": Color(0.24, 0.18, 0.14), "secondary": Color(0.34, 0.26, 0.19),
			"accent": Color(0.55, 0.48, 0.40), "dark": Color(0.11, 0.08, 0.06)},
		"shoulder_height": 1.9, "body_length": 2.9, "body_scale": 1.6,
		"speed_walk": 1.4, "speed_run": 9.0, "turn_rate": 2.0,
		"vision_range": 45.0, "vision_angle": 240.0, "hearing_range": 60.0,
		"scent_range": 110.0, "wariness": 0.5, "flee_distance": 22.0, "curiosity": 0.3,
		"biomes": {"mistwood_marsh": 1.0, "boreal_taiga": 0.9, "emerald_vale": 0.3},
		"active_hours": [[4.0, 10.0], [16.0, 23.0]],
		"herd_min": 1, "herd_max": 2, "near_water": 0.85,
		"diet": "Willow, aspen and pondweed dredged up from the shallows.",
		"habitat_note": "Boggy ground and beaver ponds. Rarely far from standing water.",
		"behaviour_note": "Unbothered by distance but dangerous up close - a moose that lays its ears back is not posing for you.",
		"features_note": "Palmate antlers spread over a metre on a prime bull. The dewlap under the throat is called a bell.",
		"track_note": "Enormous cloven print, 15 cm, often flooded with water by the time you find it.",
		"track_shape": "cloven", "track_size": 0.55,
		"has_antlers": true, "antler_points": Vector2i(6, 14),
		"weight_range": Vector2(320.0, 620.0), "photo_value": 120,
		"behaviours": ["wading", "browsing", "alert", "walking", "resting", "fleeing"],
	},
	{
		"id": "grey_wolf", "name": "Grey Wolf", "latin": "Canis lupus",
		"family": "Canidae", "size_class": "medium", "rarity": 0.78, "shape": "canine",
		"palette": {"primary": Color(0.45, 0.44, 0.43), "secondary": Color(0.62, 0.60, 0.57),
			"accent": Color(0.86, 0.85, 0.83), "dark": Color(0.18, 0.18, 0.19)},
		"shoulder_height": 0.82, "body_length": 1.6, "body_scale": 0.95,
		"speed_walk": 2.0, "speed_run": 13.0, "turn_rate": 4.2,
		"vision_range": 75.0, "vision_angle": 220.0, "hearing_range": 90.0,
		"scent_range": 140.0, "wariness": 0.8, "flee_distance": 40.0, "curiosity": 0.45,
		"biomes": {"boreal_taiga": 1.0, "emerald_vale": 0.6, "alpine_ridge": 0.5,
			"amber_woods": 0.4},
		"active_hours": [[19.0, 6.0]],
		"herd_min": 2, "herd_max": 5, "near_water": 0.2,
		"diet": "Deer, hare and whatever the winter leaves behind.",
		"habitat_note": "Deep conifer forest and the ridgelines above it. Ranges enormous distances in a night.",
		"behaviour_note": "Howls to gather the pack after dark. Will circle downwind of you before it ever shows itself.",
		"features_note": "Long legs, deep chest and a straight tail carried low. Winter coat doubles the apparent bulk.",
		"track_note": "Four toes and a triangular pad, claws printing clearly. Runs in a near-perfect straight line.",
		"track_shape": "pad", "track_size": 0.26,
		"weight_range": Vector2(32.0, 62.0), "photo_value": 160,
		"call_chance": 0.8, "call_cooldown": Vector2(14.0, 40.0),
		"behaviours": ["prowling", "howling", "alert", "walking", "resting", "fleeing", "hunting"],
	},
	{
		"id": "red_fox", "name": "Red Fox", "latin": "Vulpes vulpes",
		"family": "Canidae", "size_class": "small", "rarity": 0.35, "shape": "fox",
		"palette": {"primary": Color(0.72, 0.33, 0.13), "secondary": Color(0.86, 0.48, 0.20),
			"accent": Color(0.96, 0.94, 0.90), "dark": Color(0.16, 0.13, 0.12)},
		"shoulder_height": 0.42, "body_length": 1.05, "body_scale": 0.6,
		"speed_walk": 1.9, "speed_run": 12.0, "turn_rate": 5.5,
		"vision_range": 55.0, "vision_angle": 200.0, "hearing_range": 85.0,
		"scent_range": 90.0, "wariness": 0.66, "flee_distance": 20.0, "curiosity": 0.6,
		"biomes": {"emerald_vale": 1.0, "amber_woods": 0.9, "golden_steppe": 0.7,
			"boreal_taiga": 0.5, "mistwood_marsh": 0.4},
		"active_hours": [[18.0, 8.0]],
		"herd_min": 1, "herd_max": 1, "near_water": 0.1,
		"diet": "Voles, beetles, windfall berries. Caches surplus under moss.",
		"habitat_note": "Field edges, hedge lines and the margins of villages.",
		"behaviour_note": "Hunts voles with a high vertical pounce, ears forward, listening under the snow.",
		"features_note": "White-tipped brush of a tail, black stockings, a narrow muzzle.",
		"track_note": "A neat oval, smaller than a dog's, printed in an almost single file.",
		"track_shape": "pad", "track_size": 0.14,
		"weight_range": Vector2(4.0, 9.0), "photo_value": 70,
		"behaviours": ["prowling", "pouncing", "alert", "walking", "resting", "fleeing"],
	},
	{
		"id": "brown_bear", "name": "Brown Bear", "latin": "Ursus arctos",
		"family": "Ursidae", "size_class": "large", "rarity": 0.7, "shape": "bear",
		"palette": {"primary": Color(0.33, 0.22, 0.14), "secondary": Color(0.45, 0.31, 0.19),
			"accent": Color(0.60, 0.47, 0.33), "dark": Color(0.13, 0.09, 0.06)},
		"shoulder_height": 1.15, "body_length": 2.1, "body_scale": 1.35,
		"speed_walk": 1.6, "speed_run": 11.5, "turn_rate": 2.8,
		"vision_range": 40.0, "vision_angle": 200.0, "hearing_range": 70.0,
		"scent_range": 180.0, "wariness": 0.45, "flee_distance": 18.0, "curiosity": 0.5,
		"biomes": {"boreal_taiga": 1.0, "emerald_vale": 0.6, "alpine_ridge": 0.4,
			"mistwood_marsh": 0.5},
		"active_hours": [[5.0, 11.0], [17.0, 21.0]],
		"herd_min": 1, "herd_max": 2, "near_water": 0.5,
		"diet": "Berries, roots, carrion and fish in the shallows when the run is on.",
		"habitat_note": "Old forest with berry clearings, and any river bend where fish gather.",
		"behaviour_note": "Stands upright to read the wind. Rubs its back on marker trees and leaves hair in the bark.",
		"features_note": "A muscular shoulder hump and long straight foreclaws, pale on some individuals.",
		"track_note": "A wide hind print like a broad human foot, with five claw dots well ahead of the toes.",
		"track_shape": "claw", "track_size": 0.42,
		"weight_range": Vector2(140.0, 400.0), "photo_value": 150,
		"behaviours": ["foraging", "fishing", "standing", "walking", "resting", "fleeing", "rubbing"],
	},
	{
		"id": "wild_boar", "name": "Wild Boar", "latin": "Sus scrofa",
		"family": "Suidae", "size_class": "medium", "rarity": 0.3, "shape": "boar",
		"palette": {"primary": Color(0.26, 0.21, 0.18), "secondary": Color(0.38, 0.31, 0.25),
			"accent": Color(0.55, 0.48, 0.40), "dark": Color(0.10, 0.08, 0.07)},
		"shoulder_height": 0.78, "body_length": 1.5, "body_scale": 0.9,
		"speed_walk": 1.8, "speed_run": 10.0, "turn_rate": 3.6,
		"vision_range": 30.0, "vision_angle": 180.0, "hearing_range": 60.0,
		"scent_range": 150.0, "wariness": 0.5, "flee_distance": 18.0, "curiosity": 0.35,
		"biomes": {"amber_woods": 1.0, "mistwood_marsh": 0.8, "emerald_vale": 0.6},
		"active_hours": [[19.0, 7.0]],
		"herd_min": 2, "herd_max": 6, "near_water": 0.45,
		"diet": "Roots, tubers, acorns and anything it can turn over with its snout.",
		"habitat_note": "Damp oak woods and reed beds. Wallows in mud to shed parasites.",
		"behaviour_note": "Poor eyesight, extraordinary nose. Get downwind and you can walk astonishingly close.",
		"features_note": "Bristled ridge along the spine; boars grow tusks that wear against the upper canines.",
		"track_note": "Cloven like a deer's but rounder, with the dew claws almost always printing wide.",
		"track_shape": "cloven", "track_size": 0.24,
		"weight_range": Vector2(45.0, 150.0), "photo_value": 60,
		"behaviours": ["rooting", "wallowing", "alert", "walking", "resting", "fleeing"],
	},
	{
		"id": "snowshoe_hare", "name": "Snowshoe Hare", "latin": "Lepus americanus",
		"family": "Leporidae", "size_class": "small", "rarity": 0.22, "shape": "hare",
		"palette": {"primary": Color(0.58, 0.52, 0.45), "secondary": Color(0.78, 0.74, 0.69),
			"accent": Color(0.96, 0.96, 0.97), "dark": Color(0.18, 0.16, 0.15)},
		"shoulder_height": 0.28, "body_length": 0.52, "body_scale": 0.4,
		"speed_walk": 1.2, "speed_run": 14.0, "turn_rate": 7.0,
		"vision_range": 50.0, "vision_angle": 320.0, "hearing_range": 70.0,
		"scent_range": 55.0, "wariness": 0.85, "flee_distance": 14.0, "curiosity": 0.1,
		"biomes": {"boreal_taiga": 1.0, "alpine_ridge": 0.7, "emerald_vale": 0.4},
		"active_hours": [[17.0, 9.0]],
		"herd_min": 1, "herd_max": 2, "near_water": 0.1,
		"diet": "Bark, buds and needles through the winter; grasses when there are any.",
		"habitat_note": "Dense young spruce where it can vanish in one hop.",
		"behaviour_note": "Sits absolutely still until you are close enough to touch, then explodes sideways.",
		"features_note": "Oversized hind feet for the snow; the coat turns white by midwinter.",
		"track_note": "Two big hind prints landing ahead of the small front pair - the pattern points where it was going.",
		"track_shape": "pad", "track_size": 0.12,
		"weight_range": Vector2(1.2, 2.1), "photo_value": 45,
		"behaviours": ["feeding", "freezing", "alert", "hopping", "resting", "fleeing"],
	},
	{
		"id": "horned_owl", "name": "Great Horned Owl", "latin": "Bubo virginianus",
		"family": "Strigidae", "size_class": "small", "rarity": 0.68, "shape": "owl",
		"palette": {"primary": Color(0.42, 0.33, 0.24), "secondary": Color(0.60, 0.50, 0.38),
			"accent": Color(0.90, 0.86, 0.76), "dark": Color(0.15, 0.12, 0.09)},
		"shoulder_height": 0.55, "body_length": 0.6, "body_scale": 0.55,
		"speed_walk": 0.6, "speed_run": 9.0, "turn_rate": 6.0, "can_fly": true,
		"vision_range": 90.0, "vision_angle": 140.0, "hearing_range": 120.0,
		"scent_range": 10.0, "wariness": 0.6, "flee_distance": 22.0, "curiosity": 0.3,
		"biomes": {"emerald_vale": 0.9, "amber_woods": 1.0, "boreal_taiga": 0.7,
			"ochre_badlands": 0.4},
		"active_hours": [[20.0, 5.0]],
		"herd_min": 1, "herd_max": 1, "near_water": 0.0,
		"diet": "Hare, skunk, anything it can carry. Swallows small prey whole.",
		"habitat_note": "Perches on dead snags at the edge of clearings, hunting the open ground below.",
		"behaviour_note": "Silent in flight. Rotates its whole head to track you rather than its eyes.",
		"features_note": "Ear tufts that are not ears, a white throat patch, and enormous yellow irises.",
		"track_note": "Rarely walks. Look instead for pellets of bone and fur beneath its perch.",
		"track_shape": "bird", "track_size": 0.16,
		"weight_range": Vector2(1.0, 2.5), "photo_value": 130,
		"call_chance": 0.85,
		"behaviours": ["perching", "hunting", "alert", "flying", "resting", "fleeing"],
	},
	{
		"id": "raven", "name": "Common Raven", "latin": "Corvus corax",
		"family": "Corvidae", "size_class": "small", "rarity": 0.15, "shape": "corvid",
		"palette": {"primary": Color(0.10, 0.10, 0.13), "secondary": Color(0.18, 0.18, 0.23),
			"accent": Color(0.36, 0.36, 0.44), "dark": Color(0.05, 0.05, 0.07)},
		"shoulder_height": 0.32, "body_length": 0.62, "body_scale": 0.45,
		"speed_walk": 1.0, "speed_run": 11.0, "turn_rate": 6.5, "can_fly": true,
		"vision_range": 100.0, "vision_angle": 300.0, "hearing_range": 70.0,
		"scent_range": 20.0, "wariness": 0.4, "flee_distance": 16.0, "curiosity": 0.8,
		"biomes": {"emerald_vale": 0.8, "amber_woods": 0.8, "boreal_taiga": 0.9,
			"alpine_ridge": 1.0, "ochre_badlands": 0.9, "golden_steppe": 0.8,
			"mistwood_marsh": 0.6},
		"active_hours": [[6.0, 19.0]],
		"herd_min": 1, "herd_max": 4, "near_water": 0.0,
		"diet": "Opportunist. Carrion, eggs, grain, and whatever it steals from a wolf kill.",
		"habitat_note": "Everywhere. Follows predators and hunters alike, waiting.",
		"behaviour_note": "Plays in updraughts along cliffs. A gathering of ravens usually means something has died nearby.",
		"features_note": "Wedge-shaped tail and shaggy throat hackles distinguish it from a crow.",
		"track_note": "Three forward toes and one back, printed in mud around carrion.",
		"track_shape": "bird", "track_size": 0.13,
		"weight_range": Vector2(0.8, 1.6), "photo_value": 35,
		"behaviours": ["perching", "scavenging", "alert", "flying", "calling", "fleeing"],
	},
	{
		"id": "mallard", "name": "Mallard", "latin": "Anas platyrhynchos",
		"family": "Anatidae", "size_class": "small", "rarity": 0.12, "shape": "duck",
		"palette": {"primary": Color(0.16, 0.35, 0.24), "secondary": Color(0.62, 0.52, 0.36),
			"accent": Color(0.86, 0.78, 0.55), "dark": Color(0.12, 0.11, 0.10)},
		"shoulder_height": 0.26, "body_length": 0.58, "body_scale": 0.42,
		"speed_walk": 0.8, "speed_run": 9.5, "turn_rate": 5.0, "can_fly": true, "swims": true,
		"vision_range": 60.0, "vision_angle": 300.0, "hearing_range": 50.0,
		"scent_range": 15.0, "wariness": 0.55, "flee_distance": 18.0, "curiosity": 0.2,
		"biomes": {"mistwood_marsh": 1.0, "emerald_vale": 0.5, "golden_steppe": 0.3},
		"active_hours": [[5.0, 20.0]],
		"herd_min": 3, "herd_max": 9, "near_water": 1.0,
		"diet": "Dabbles for seeds, snails and pondweed, tail up in the shallows.",
		"habitat_note": "Any still water with a reedy edge.",
		"behaviour_note": "Erupts almost vertically off the water when spooked - be ready before you are close.",
		"features_note": "The drake's bottle-green head and the blue speculum flash on both sexes.",
		"track_note": "Webbed triangles in the mud, usually crowded along the waterline.",
		"track_shape": "bird", "track_size": 0.11,
		"weight_range": Vector2(0.9, 1.4), "photo_value": 30,
		"behaviours": ["dabbling", "swimming", "preening", "flying", "resting", "fleeing"],
	},
	{
		"id": "bighorn_ram", "name": "Bighorn Ram", "latin": "Ovis canadensis",
		"family": "Bovidae", "size_class": "medium", "rarity": 0.66, "shape": "ram",
		"palette": {"primary": Color(0.52, 0.45, 0.37), "secondary": Color(0.66, 0.60, 0.51),
			"accent": Color(0.90, 0.88, 0.83), "dark": Color(0.24, 0.20, 0.16)},
		"shoulder_height": 0.98, "body_length": 1.6, "body_scale": 1.0,
		"speed_walk": 1.4, "speed_run": 9.0, "turn_rate": 3.0,
		"vision_range": 110.0, "vision_angle": 250.0, "hearing_range": 45.0,
		"scent_range": 70.0, "wariness": 0.7, "flee_distance": 34.0, "curiosity": 0.2,
		"biomes": {"alpine_ridge": 1.0, "ochre_badlands": 0.5},
		"active_hours": [[5.5, 11.0], [15.0, 20.0]],
		"herd_min": 2, "herd_max": 6, "near_water": 0.15,
		"altitude_pref": Vector2(40.0, 999.0),
		"diet": "Alpine grasses and lichen scraped off rock.",
		"habitat_note": "Broken cliff faces where it can climb away from anything that follows.",
		"behaviour_note": "Watches you from above long before you see it. Rams clash horns through the autumn.",
		"features_note": "Massive curling horns that never shed - count the growth rings for its age.",
		"track_note": "A blocky cloven print with straighter edges than a deer's, gripping rock.",
		"track_shape": "cloven", "track_size": 0.28,
		"has_antlers": true, "antler_points": Vector2i(1, 1),
		"weight_range": Vector2(60.0, 140.0), "photo_value": 140,
		"behaviours": ["grazing", "climbing", "alert", "walking", "resting", "fleeing", "clashing"],
	},
	{
		"id": "pronghorn", "name": "Pronghorn", "latin": "Antilocapra americana",
		"family": "Antilocapridae", "size_class": "medium", "rarity": 0.4, "shape": "pronghorn",
		"palette": {"primary": Color(0.74, 0.58, 0.33), "secondary": Color(0.90, 0.82, 0.66),
			"accent": Color(0.98, 0.97, 0.94), "dark": Color(0.20, 0.16, 0.12)},
		"shoulder_height": 0.9, "body_length": 1.4, "body_scale": 0.9,
		"speed_walk": 2.2, "speed_run": 18.0, "turn_rate": 4.0,
		"vision_range": 160.0, "vision_angle": 300.0, "hearing_range": 50.0,
		"scent_range": 60.0, "wariness": 0.9, "flee_distance": 55.0, "curiosity": 0.35,
		"biomes": {"golden_steppe": 1.0, "ochre_badlands": 0.7},
		"active_hours": [[5.0, 20.0]],
		"herd_min": 3, "herd_max": 10, "near_water": 0.2,
		"diet": "Sagebrush and forbs the cattle will not touch.",
		"habitat_note": "Wide open grassland where it can see a mile in every direction.",
		"behaviour_note": "The fastest thing on the plain, and it knows it. Flares its white rump patch as an alarm you can see from a ridge away.",
		"features_note": "Pronged horns with a shed outer sheath, and huge dark eyes set far back.",
		"track_note": "A narrow cloven print with no dew claws, spaced impossibly far apart at speed.",
		"track_shape": "cloven", "track_size": 0.22,
		"has_antlers": true, "antler_points": Vector2i(2, 2),
		"weight_range": Vector2(35.0, 65.0), "photo_value": 95,
		"behaviours": ["grazing", "sprinting", "alert", "walking", "resting", "fleeing"],
	},
	{
		"id": "bobcat", "name": "Bobcat", "latin": "Lynx rufus",
		"family": "Felidae", "size_class": "small", "rarity": 0.8, "shape": "cat",
		"palette": {"primary": Color(0.66, 0.50, 0.33), "secondary": Color(0.80, 0.68, 0.50),
			"accent": Color(0.94, 0.91, 0.85), "dark": Color(0.20, 0.16, 0.12)},
		"shoulder_height": 0.52, "body_length": 0.95, "body_scale": 0.62,
		"speed_walk": 1.4, "speed_run": 12.5, "turn_rate": 6.0,
		"vision_range": 70.0, "vision_angle": 200.0, "hearing_range": 95.0,
		"scent_range": 80.0, "wariness": 0.88, "flee_distance": 26.0, "curiosity": 0.2,
		"biomes": {"ochre_badlands": 1.0, "amber_woods": 0.5, "golden_steppe": 0.4,
			"alpine_ridge": 0.3},
		"active_hours": [[18.0, 8.0]],
		"herd_min": 1, "herd_max": 1, "near_water": 0.1,
		"diet": "Rabbit, chiefly. Will take a bird off a branch if the chance comes.",
		"habitat_note": "Rock breaks and canyon shadow. Uses the same ledges night after night.",
		"behaviour_note": "The hardest animal here to photograph. Moves at the edge of your vision and is gone if you look straight at it.",
		"features_note": "Barred forelegs, black ear tufts, and the short black-tipped tail it is named for.",
		"track_note": "Round, four toes, no claw marks - cats walk with the claws sheathed.",
		"track_shape": "round", "track_size": 0.15,
		"weight_range": Vector2(6.0, 16.0), "photo_value": 200,
		"behaviours": ["stalking", "perching", "alert", "walking", "resting", "fleeing"],
	},
	{
		"id": "river_otter", "name": "River Otter", "latin": "Lontra canadensis",
		"family": "Mustelidae", "size_class": "small", "rarity": 0.55, "shape": "otter",
		"palette": {"primary": Color(0.31, 0.23, 0.17), "secondary": Color(0.45, 0.35, 0.26),
			"accent": Color(0.78, 0.72, 0.62), "dark": Color(0.13, 0.10, 0.08)},
		"shoulder_height": 0.3, "body_length": 1.1, "body_scale": 0.5,
		"speed_walk": 1.3, "speed_run": 8.0, "turn_rate": 6.5, "swims": true,
		"vision_range": 45.0, "vision_angle": 220.0, "hearing_range": 55.0,
		"scent_range": 50.0, "wariness": 0.5, "flee_distance": 16.0, "curiosity": 0.75,
		"biomes": {"mistwood_marsh": 1.0, "emerald_vale": 0.4, "boreal_taiga": 0.4},
		"active_hours": [[5.0, 10.0], [16.0, 21.0]],
		"herd_min": 1, "herd_max": 3, "near_water": 1.0,
		"diet": "Fish, crayfish and frogs, eaten on a favourite flat rock.",
		"habitat_note": "Slow river bends and beaver ponds with undercut banks.",
		"behaviour_note": "Genuinely playful - slides down muddy banks over and over. Curious enough to swim closer for a look at you.",
		"features_note": "Thick tapering tail, webbed feet, and fur so dense it never actually gets wet.",
		"track_note": "Five toes, webbing sometimes printing, alongside a drag mark from the tail.",
		"track_shape": "pad", "track_size": 0.13,
		"weight_range": Vector2(5.0, 14.0), "photo_value": 110,
		"behaviours": ["swimming", "sliding", "eating", "alert", "resting", "fleeing"],
	},

	# --------------------------------------------------------------- legendary
	# Three animals that are meant to be stories rather than entries. They are
	# rare enough that most expeditions never turn one up, wary enough that a
	# careless approach loses them, and worth enough that one good frame pays
	# for a lens.
	{
		"id": "albino_deer", "name": "The White Doe", "latin": "Odocoileus virginianus",
		"family": "Cervidae", "size_class": "medium", "rarity": 0.97, "shape": "deer",
		"palette": {"primary": Color(0.94, 0.93, 0.90), "secondary": Color(0.99, 0.98, 0.96),
			"accent": Color(1.0, 1.0, 1.0), "dark": Color(0.82, 0.78, 0.76)},
		"shoulder_height": 1.10, "body_length": 1.85, "body_scale": 1.03,
		"speed_walk": 1.4, "speed_run": 13.0, "turn_rate": 3.6,
		"vision_range": 78.0, "vision_angle": 280.0, "hearing_range": 62.0,
		"scent_range": 105.0, "wariness": 0.94, "flee_distance": 42.0, "curiosity": 0.06,
		"biomes": {"emerald_vale": 0.05, "amber_woods": 0.05, "mistwood_marsh": 0.03},
		"active_hours": [[4.0, 7.0], [19.0, 22.0]],
		"herd_min": 1, "herd_max": 1, "near_water": 0.4,
		"diet": "The same browse as any whitetail. Feeds alone, and only at the edges of the day.",
		"habitat_note": "Deep mixed woodland. Keeps to mist and half-light, and is almost never seen in open sun.",
		"behaviour_note": "Will not tolerate an approach inside forty metres. Vanishes rather than bolts - look away once and she is gone.",
		"features_note": "True albino: unpigmented coat, pale hooves, pink eyes that catch the light and hold it.",
		"track_note": "A whitetail's print, no different from any other. Only the company it keeps gives her away.",
		"track_shape": "cloven", "track_size": 0.30,
		"has_antlers": false, "antler_points": Vector2i(0, 0),
		"weight_range": Vector2(48.0, 96.0), "photo_value": 420,
		"behaviours": ["grazing", "browsing", "alert", "walking", "resting", "fleeing"],
	},
	{
		"id": "black_wolf", "name": "The Black Wolf", "latin": "Canis lupus",
		"family": "Canidae", "size_class": "large", "rarity": 0.96, "shape": "canine",
		"palette": {"primary": Color(0.11, 0.10, 0.12), "secondary": Color(0.18, 0.17, 0.20),
			"accent": Color(0.30, 0.29, 0.33), "dark": Color(0.05, 0.05, 0.06)},
		"shoulder_height": 0.92, "body_length": 1.75, "body_scale": 1.15,
		"speed_walk": 2.0, "speed_run": 15.0, "turn_rate": 4.2,
		"vision_range": 90.0, "vision_angle": 250.0, "hearing_range": 105.0,
		"scent_range": 150.0, "wariness": 0.80, "flee_distance": 26.0, "curiosity": 0.42,
		"biomes": {"emerald_vale": 0.04, "amber_woods": 0.04, "frostpine_reach": 0.06,
			"stonecrag_pass": 0.04},
		"active_hours": [[0.0, 6.0], [20.0, 24.0]],
		"herd_min": 1, "herd_max": 1, "near_water": 0.2,
		"diet": "Takes deer, hare and whatever the winter leaves behind. Hunts alone by choice.",
		"habitat_note": "Ranges further than any pack - old burns, high passes and the dark side of ridges.",
		"behaviour_note": "Holds its ground and looks straight back at you, which is worse than fleeing. Answers howls it likes the sound of.",
		"features_note": "Melanistic and half again the size of a grey. Pale scar across the muzzle, one ear notched.",
		"track_note": "A wolf's pad, but wider than it should be, and the stride between prints is longer than seems reasonable.",
		"track_shape": "pad", "track_size": 0.24,
		"weight_range": Vector2(58.0, 84.0), "photo_value": 480,
		"behaviours": ["walking", "alert", "hunting", "resting", "howling", "fleeing"],
	},
	{
		"id": "golden_eagle", "name": "Golden Eagle", "latin": "Aquila chrysaetos",
		"family": "Accipitridae", "size_class": "medium", "rarity": 0.92, "shape": "owl",
		"palette": {"primary": Color(0.29, 0.20, 0.12), "secondary": Color(0.46, 0.33, 0.18),
			"accent": Color(0.86, 0.68, 0.30), "dark": Color(0.14, 0.10, 0.07)},
		"shoulder_height": 0.55, "body_length": 0.95, "body_scale": 1.5,
		"speed_walk": 1.2, "speed_run": 22.0, "turn_rate": 2.6,
		"can_fly": true,
		"vision_range": 160.0, "vision_angle": 210.0, "hearing_range": 50.0,
		"scent_range": 0.0, "wariness": 0.72, "flee_distance": 48.0, "curiosity": 0.15,
		"biomes": {"stonecrag_pass": 0.09, "frostpine_reach": 0.05, "golden_steppe": 0.05},
		"active_hours": [[7.0, 18.0]],
		"herd_min": 1, "herd_max": 1, "near_water": 0.0,
		"altitude_pref": Vector2(60.0, 999.0),
		"diet": "Hare, marmot and carrion, taken in a stoop that starts too high to see.",
		"habitat_note": "Cliffs and high ridges. Rides the updraught along a rock face for hours without a wingbeat.",
		"behaviour_note": "Almost never on the ground where you can reach it. The photograph everyone wants is the one with the wings open.",
		"features_note": "Two-metre span, dark brown with the gold hackles on the nape that give it the name.",
		"track_note": "Rarely leaves one. Look instead for scattered feathers and a plucking post on a flat rock.",
		"track_shape": "bird", "track_size": 0.16,
		"weight_range": Vector2(3.0, 6.5), "photo_value": 460,
		"behaviours": ["soaring", "perched", "alert", "hunting", "fleeing"],
	},
]

static var _cache: Dictionary = {}


static func all() -> Array:
	_ensure_cache()
	return _cache.values()


static func ids() -> Array:
	_ensure_cache()
	return _cache.keys()


static func get_species(id: String) -> Species:
	_ensure_cache()
	return _cache.get(id, null)


static func _ensure_cache() -> void:
	if not _cache.is_empty():
		return
	for entry: Dictionary in DATA:
		var s := Species.from_dict(entry)
		_cache[s.id] = s


## Species that can spawn in a biome, paired with their weight.
static func for_biome(biome_id: String) -> Array:
	_ensure_cache()
	var out: Array = []
	for s: Species in _cache.values():
		var w := s.biome_weight(biome_id)
		if w > 0.0:
			out.append({"species": s, "weight": w})
	return out


static func total_count() -> int:
	return DATA.size()
